import { Movie,Series } from './movie';

import { Categories } from "./categories";

export const MovieList: Movie[] = [
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'Sabotage', poster: 'https://www.themoviedb.org/t/p/w1280/f5L0WlOAzFiKTOGNZTcKkEJ4iOT.jpg', year: 2014, category: Categories.Action},
  {title: 'Sonic the Hedgehog 2', poster: 'https://www.themoviedb.org/t/p/w1280/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg', year: 2022, category: Categories.Comedy},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'Sabotage', poster: 'https://www.themoviedb.org/t/p/w1280/f5L0WlOAzFiKTOGNZTcKkEJ4iOT.jpg', year: 2014, category: Categories.Action},
  {title: 'Sonic the Hedgehog 2', poster: 'https://www.themoviedb.org/t/p/w1280/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg', year: 2022, category: Categories.Comedy},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'Sabotage', poster: 'https://www.themoviedb.org/t/p/w1280/f5L0WlOAzFiKTOGNZTcKkEJ4iOT.jpg', year: 2014, category: Categories.Action},
  {title: 'Sonic the Hedgehog 2', poster: 'https://www.themoviedb.org/t/p/w1280/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg', year: 2022, category: Categories.Comedy},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'The Shawshank Redemption', poster: 'https://www.themoviedb.org/t/p/w1280/7Ch8iOwNlqgJYQcqSxOvPIwj5S4.jpg', year: 1994, category: Categories.Drama},
  {title: 'The Godfather', poster: 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', year: 1972, category: Categories.Crime},
  {title: 'The Godfather: Part II', poster: 'https://www.themoviedb.org/t/p/w1280/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg', year: 1974, category: Categories.Crime},
  {title: 'The Dark Knight', poster: 'https://www.themoviedb.org/t/p/w1280/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg', year: 2008, category: Categories.Action},
  {title: 'Sabotage', poster: 'https://www.themoviedb.org/t/p/w1280/f5L0WlOAzFiKTOGNZTcKkEJ4iOT.jpg', year: 2014, category: Categories.Action},
  {title: 'Sonic the Hedgehog 2', poster: 'https://www.themoviedb.org/t/p/w1280/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg', year: 2022, category: Categories.Comedy},
  
];

export const SeriesList: Series[] = [
  {title: 'The Walking Dead', poster: 'https://www.themoviedb.org/t/p/w1280/rqeYMLryjcawh2JeRpCVUDXYM5b.jpg', year: 2010, episodes: 1, category: Categories.Drama},
  {title: 'The Walking Dead', poster: 'https://www.themoviedb.org/t/p/w1280/rqeYMLryjcawh2JeRpCVUDXYM5b.jpg', year: 2010, episodes: 2, category: Categories.Drama},
  {title: 'The Walking Dead', poster: 'https://www.themoviedb.org/t/p/w1280/rqeYMLryjcawh2JeRpCVUDXYM5b.jpg', year: 2010, episodes: 3, category: Categories.Drama},
  {title: 'The Walking Dead', poster: 'https://www.themoviedb.org/t/p/w1280/rqeYMLryjcawh2JeRpCVUDXYM5b.jpg', year: 2010, episodes: 4, category: Categories.Drama},  
  {title: 'The Walking Dead', poster: 'https://www.themoviedb.org/t/p/w1280/rqeYMLryjcawh2JeRpCVUDXYM5b.jpg', year: 2010, episodes: 5, category: Categories.Drama},
];

