name: Docs

on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  nuget_feed_name: 'DCR.Dev2'
  nuget_feed_source: 'https://pkgs.dev.azure.com/myteo/DCRSolutions/_packaging/DCR.dev.2/nuget/v3/index.json'

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - run: dotnet nuget remove source nuget.org

    - name: Auth NuGet
      run: dotnet nuget add source ${{ env.nuget_feed_source }} --name ${{ env.nuget_feed_name }} --username az --password ${{ secrets.AZURE_DEVOPS_TOKEN }}

    - run: dotnet tool update docfx -g
    
